# .pre-commit-config.yaml
#
# For more info: https://pre-commit.com
# To run all hooks on all files: pre-commit run --all-files

repos:
  # -----------------------------------------------------
  # Optional: General code quality/linting hooks (useful for any project)
  # Examples: checking for large files, trailing whitespace, end-of-file-fixer
  # -----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the latest stable version
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ['--maxkb=2048'] # Warn if adding files larger than 2MB
      # - id: forbid-binary # Uncomment to prevent committing any binary files

  # - repo: local
  #   hooks:
  #     - id: ai-sql-review
  #       name: AI SQL Code Review
  #       entry: python3 ai_code_reviewer.py
  #       additional_dependencies:
  #         - google-genai
  #       language: python
  #       pass_filenames: false
  #       args: ['--project', 'cts-sbx-1f2-upbeat-hermann', '--location', 'europe-west4','--sql_dir','./sql']
  #       types: [sql]
  #       exclude_types:
  #         - markdown

  - repo: https://github.com/kev-pinto-qodea/ai-sql-reviewer-hook
    rev: v0.1.0 # Use the latest stable version
    hooks:
      - id: ai-sql-review
        pass_filenames: false
        args:
          - "--project=cts-sbx-1f2-upbeat-hermann"
          - "--location=europe-west4"
          - "--sql_dir=./sql" # Directory containing SQL files
      # pre-commit inherently handles the files it matches.
      # Your script receives the files as positional arguments.
